# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb866d46d7721f7905314a3f9c5ab13fcb315f66d9630fd070521bbfca74ffc563b4f796502bdae21c395d618d4f22702b00e5871b155a37155f9dce12e8e721

test:
  secret_key_base: f6d93fabb4bd45c1841703704d496f034c65799c0453287b6f2dce0ff1eaa2575a0044e1f3ed59cae70e6ff77cbd18476da764fdd2733ff72e48afe30a045890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
